### ISSUE TITLE
No appropriate protocol (protocol is disabled or cipher suites are inappropriate)

### ISSUE THREAD

**Issue by ChenSino** [code4craft/webmagic#1109]
版本：0.7.3
代码：[文档中的第一个爬虫项目demo ](http://webmagic.io/docs/zh/posts/ch2-install/first-project.html)
之前有人提过issue：https://github.com/code4craft/webmagic/issues/1069

```bash
[WARN ] 2023-02-15 13:38:34,730(206) --> [pool-1-thread-1] us.codecraft.webmagic.downloader.HttpClientDownloader.download(HttpClientDownloader.java:91): download page https://github.com/code4craft error  
javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
	at java.base/sun.security.ssl.HandshakeContext.<init>(HandshakeContext.java:170)
	at java.base/sun.security.ssl.ClientHandshakeContext.<init>(ClientHandshakeContext.java:103)
	at java.base/sun.security.ssl.TransportContext.kickstart(TransportContext.java:222)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:449)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:427)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:394)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:353)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at us.codecraft.webmagic.downloader.HttpClientDownloader.download(HttpClientDownloader.java:85)
	at us.codecraft.webmagic.Spider.processRequest(Spider.java:404)
	at us.codecraft.webmagic.Spider.access$000(Spider.java:61)
	at us.codecraft.webmagic.Spider$1.run(Spider.java:320)
	at us.codecraft.webmagic.thread.CountableThreadPool$1.run(CountableThreadPool.java:74)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
[INFO ] 2023-02-15 13:38:34,835(311) --> [main] us.codecraft.webmagic.Spider.run(Spider.java:338): Spider github.com closed! 1 pages downloaded.  

```

**Comment by ChenSino** [comment]
已解决：
1. 升级webmagic版本，我从0.7.3升级到了0.8.0
2. 修改java.security配置，到文件中找到jdk.tls.diabledAlgorithms,去掉后面的SSLv3  TLSv1 TLSv1.1
3. 重新运行代码
