### ISSUE TITLE
使用RedisScheduler会报找不到rpush方法,使用默认的Schduler正常。

### ISSUE THREAD

**Issue by hackeryutu** [code4craft/webmagic#1143]
Exception in thread "main" java.lang.NoSuchMethodError: 'java.lang.Long redis.clients.jedis.Jedis.rpush(java.lang.String, java.lang.String[])'
	at us.codecraft.webmagic.scheduler.RedisScheduler.pushWhenNoDuplicate(RedisScheduler.java:59)
	at us.codecraft.webmagic.scheduler.DuplicateRemovedScheduler.push(DuplicateRemovedScheduler.java:37)
	at us.codecraft.webmagic.Spider.addRequest(Spider.java:514)
	at us.codecraft.webmagic.Spider.addRequest(Spider.java:589)

**Comment by hackeryutu** [comment]
spring boot把jedis的版本变成4.x了
