### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchFieldError: INSTANCE

### ISSUE THREAD

**Issue by fuli66** [code4craft/webmagic#1165]
`Exception in thread "main" java.lang.NoSuchFieldError: INSTANCE
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:146)
	at us.codecraft.webmagic.downloader.HttpClientGenerator.buildSSLConnectionSocketFactory(HttpClientGenerator.java:52)
	at us.codecraft.webmagic.downloader.HttpClientGenerator.<init>(HttpClientGenerator.java:44)
	at us.codecraft.webmagic.downloader.HttpClientDownloader.<init>(HttpClientDownloader.java:40)
	at us.codecraft.webmagic.Spider.initComponent(Spider.java:280)
	at us.codecraft.webmagic.Spider.run(Spider.java:305)
	at com.mufeng.spider.GithubRepoPageProcessor.main(GithubRepoPageProcessor.java:30)`

**Comment by sutra** [comment]
Could you provide the output of `mvn dependency:tree`.
