### ISSUE TITLE
使用webmagic构建请求，报错：handshake_failure

### ISSUE THREAD

**Issue by Bizhi-1024** [code4craft/webmagic#1184]
下一个版本是否可以支持以下类型的网站呢？
目标URL：https://ggzyjy.xuancheng.gov.cn/
报错信息：
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:347)
	at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:186)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1511)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1421)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:456)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:427)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at us.codecraft.webmagic.downloader.HttpClientDownloader.proceed(HttpClientDownloader.java:57)
	at us.codecraft.webmagic.downloader.DownloadContext.proceed(DownloadContext.java:40)
	at com.huayu.spider.middleware.SkipProxyDownloadMiddleware.proceed(SkipProxyDownloadMiddleware.java:25)
	at us.codecraft.webmagic.downloader.DownloadContext.proceed(DownloadContext.java:40)
	at us.codecraft.webmagic.downloader.HttpClientDownloader.download(HttpClientDownloader.java:81)

**Comment by sutra** [comment]
webmagic 版本号？

**Comment by Bizhi-1024** [comment]
1.0.1 最新版本

**Comment by sutra** [comment]
该网站所使用的证书的根证书 China Financial Certification Authority, CFCA EV ROOT, (E2:B8:29:4B:55:84:AB:6B:58:C2:90:46:6C:AC:3F:B8:39:8F:84:83) [不被 JDK 支持](https://ionite.net/newsblog/2020-06-29_peppol_tls_certificates/)。
