### ISSUE TITLE
执行ZipCodePageProcessor类测试报错

### ISSUE THREAD

**Issue by huguangju** [code4craft/webmagic#189]
``` java
java.lang.IllegalStateException: Target host is null
    at org.apache.http.util.Asserts.notNull(Asserts.java:46)
    at org.apache.http.impl.client.InternalHttpClient.determineRoute(InternalHttpClient.java:125)
    at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
    at us.codecraft.webmagic.downloader.HttpClientDownloader.download(HttpClientDownloader.java:92)
    at us.codecraft.webmagic.Spider.processRequest(Spider.java:408)
    at us.codecraft.webmagic.Spider$1.run(Spider.java:322)
    at us.codecraft.webmagic.thread.CountableThreadPool$1.run(CountableThreadPool.java:74)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
```

打断点到

``` java
private void processCountry(Page page) {
        List<String> provinces = page.getHtml().xpath("//*[@id=\"newAlexa\"]/table/tbody/tr/td").all();
        for (String province : provinces) {
            String link = xpath("//@href").select(province);
            String title = xpath("/text()").select(province);
            Request request = new Request(link).setPriority(0).putExtra("province", title);
            page.addTargetRequest(request);
        }
    }
```

中的

``` java
String link = xpath("//@href").select(province);
String title = xpath("/text()").select(province);
```

这两句时，发现link和title的值都为空字符串，`province`确实有值： 
&lt;td width="20%">&lt;a href="http://www.ip138.com/10/" target="_blank">北京市&lt;/a>&lt;/td>

不知是xpath语法错误还是解析错误？

**Comment by code4craft** [comment]
应该是页面改版的原因，参考一下其他的示例吧~
