### ISSUE TITLE
Selectable.nodes.get(0).xpath("@href") 出错

### ISSUE THREAD

**Issue by nikytwo** [code4craft/webmagic#200]
这样是没有问题的。
```Java
    page.getHtml().xpath("//a[1]/@href");
```
但如下使用时提示：java.lang.NullPointerException
```Java
   page.getHtml().xpath("//a[1]").nodes().get(0).xpath("@href");
```
`page.getHtml().xpath("//a[1]").nodes().get(0)`可以返回正确的对象。

**Comment by code4craft** [comment]
已确认，@href这类不选择元素的xpath在xsoup中会出错。[Xsoup #15](https://github.com/code4craft/xsoup/issues/15)

```java
java.lang.NullPointerException
	at org.jsoup.select.Collector$Accumulator.head(Collector.java:42)
	at org.jsoup.select.NodeTraversor.traverse(NodeTraversor.java:30)
	at org.jsoup.select.Collector.collect(Collector.java:24)
	at us.codecraft.xsoup.DefaultXPathEvaluator.evaluate(DefaultXPathEvaluator.java:27)
	at us.codecraft.webmagic.selector.XpathSelector.selectList(XpathSelector.java:31)
	at us.codecraft.webmagic.selector.HtmlNode.selectElements(HtmlNode.java:80)
	at us.codecraft.webmagic.selector.HtmlNode.xpath(HtmlNode.java:43)
```

**Comment by code4craft** [comment]
在0.5.3中已修复。
