### ISSUE TITLE
页面下载的时候Timeout，爬虫线程直接死掉了

### ISSUE THREAD

**Issue by donsunsoft** [code4craft/webmagic#224]
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(SocketInputStream.java:152)
	at java.net.SocketInputStream.read(SocketInputStream.java:122)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:136)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:152)
	at org.apache.http.impl.io.SessionInputBufferImpl.read(SessionInputBufferImpl.java:203)
	at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:174)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:137)
	at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:238)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
	at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:116)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at org.apache.http.client.entity.LazyDecompressingInputStream.read(LazyDecompressingInputStream.java:68)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1025)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:999)
	at org.apache.commons.io.IOUtils.toByteArray(IOUtils.java:218)
	at us.codecraft.webmagic.downloader.HttpClientDownloader.getContent(HttpClientDownloader.java:189)
	at us.codecraft.webmagic.downloader.HttpClientDownloader.handleResponse(HttpClientDownloader.java:178)
	at us.codecraft.webmagic.downloader.HttpClientDownloader.download(HttpClientDownloader.java:96)
	at us.codecraft.webmagic.Spider.processRequest(Spider.java:410)
	at us.codecraft.webmagic.Spider$1.run(Spider.java:324)
	at us.codecraft.webmagic.thread.CountableThreadPool$1.run(CountableThreadPool.java:74)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by yuchaozhou** [comment]
请详细说一下是否多线程，程序运行环境等信息，保证BUG可复现。

**Comment by code4craft** [comment]
最外层有try-catch，理论上不会有这种情况。这个似乎只是堆栈打印出来了？

**Comment by YdjJervis** [comment]
@yuchaozhou 请问这个问题解决了吗？我也遇到了

**Comment by kangyu06** [comment]
我也遇到了啊啊啊啊啊啊啊啊啊
