### ISSUE TITLE
jsoup从1.8.1升级到1.8.2或以上，会报错

### ISSUE THREAD

**Issue by suliuyes** [code4craft/webmagic#245]
Exception in thread "pool-2-thread-2" java.lang.NoSuchMethodError: org.jsoup.select.Elements.get(I)Lorg/jsoup/nodes/Element;
	at us.codecraft.xsoup.XEvaluators$IsNthOfType.calculatePosition(XEvaluators.java:30)
	at org.jsoup.select.Evaluator$CssNthEvaluator.matches(Evaluator.java:419)
	at us.codecraft.xsoup.CombiningEvaluator$And.matches(CombiningEvaluator.java:53)
	at us.codecraft.xsoup.CombiningEvaluator$And.matches(CombiningEvaluator.java:53)
	at org.jsoup.select.Collector$Accumulator.head(Collector.java:42)
	at org.jsoup.select.NodeTraversor.traverse(NodeTraversor.java:31)
	at org.jsoup.select.Collector.collect(Collector.java:24)
	at us.codecraft.xsoup.DefaultXPathEvaluator.evaluate(DefaultXPathEvaluator.java:27)
	at us.codecraft.webmagic.selector.XpathSelector.selectList(XpathSelector.java:32)
	at us.codecraft.webmagic.selector.HtmlNode.selectElements(HtmlNode.java:80)
	at us.codecraft.webmagic.selector.HtmlNode.xpath(HtmlNode.java:43)

使用page.getHtml().xpath().get()，1.8.1一直使用正常。升级到1.8.2以上就会报这个异常。但不是每个地方都报。
这里有相关兼容性报告,应该是Removed了get method导致的：
http://upstream.rosalinux.ru/java/compat_reports/jsoup/1.8.1_to_1.8.2/bin_compat_report.html

**Comment by chy996633** [comment]
为什么这里涉及到Jsoup呢，源码里面get()就只是从集合里取出第一个元素呀？

**Comment by code4craft** [comment]
我这边没有办法复现，看源码也是有`org.jsoup.select.Elements.get(I)`这个方法的。怀疑是编译问题。

**Comment by code4craft** [comment]
已复现，将Xsoup升级到0.3.1搞定了。
