### ISSUE TITLE
运行第一个demo时出错。

### ISSUE THREAD

**Issue by theoneLee** [code4craft/webmagic#281]
http://webmagic.io/docs/zh/posts/ch2-install/first-project.html
这里的demo并不能成功运行。然后试了下面的demo。github上的demo。报错都是一致的。
刚接触爬虫。望作者大大指教。

报错信息：

`Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/collect/Table
	at test.GithubRepoPageProcessor.<init>(GithubRepoPageProcessor.java:55)
	at test.GithubRepoPageProcessor.main(GithubRepoPageProcessor.java:75)
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.Table
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 2 more
`

**Comment by youyouYoung** [comment]
你没有导入jar包.可以在<a href='http://webmagic.io/'>这里</a>的下载部分,下载到项目依赖的所有jar包.

**Comment by theoneLee** [comment]
导入包是肯定的。我手册跟着过来的。

**Comment by code4craft** [comment]
Guava版本有问题。你是不是还依赖了其他版本的jar包？

**Comment by theoneLee** [comment]
@youyouYoung 是对的。实在抱歉。之前还认为你是错的。我重新看了作者大大的手册。之前是自己疏忽，以为自己看清楚了。然后没导入依赖包。只导入了webmagic核心包。 @code4craft 也谢谢作者大大来答复。

**Comment by youyouYoung** [comment]
@theoneLee 手动笑脸

**Comment by le0zh0u** [comment]
我自己建了一个项目，
导入了<dependency>
			<groupId>us.codecraft</groupId>
			<artifactId>webmagic-core</artifactId>
			<version>0.5.3</version>
		</dependency>
		<dependency>
			<groupId>us.codecraft</groupId>
			<artifactId>webmagic-extension</artifactId>
			<version>0.5.3</version>
		</dependency>
运行之后报
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/collect/Table
	at com.leozhou.webmagic.GithubRepoPageProcessor.<init>(GithubRepoPageProcessor.java:14)
	at com.leozhou.webmagic.GithubRepoPageProcessor.main(GithubRepoPageProcessor.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.Table
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more

**Comment by theoneLee** [comment]
@le0zh0u 和我问题一样啊。之前用时没导入相关的依赖包。只导了webmagic的包。你看清楚code4craft 写的教程。[http://webmagic.qiniudn.com/all-dependencies-0.5.2.tar.gz](url)

**Comment by le0zh0u** [comment]
额。。在教程里是有两个依赖的包的。我都写到POM里了。后来发现是有一个包可能是国内的问题，没有下载下来。所以报错了。。后来单独下了下来，能跑起来，但是报连接超时了，😂
