### ISSUE TITLE
Run the first demo GithubRepoPageProcessor post the format exception

### ISSUE THREAD

**Issue by jinyun** [code4craft/webmagic#282]
log4j:ERROR Category option " 1 " not a decimal integer.
java.lang.NumberFormatException: For input string: " 1 "
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:481)
	at java.lang.Integer.parseInt(Integer.java:527)
	at org.apache.log4j.helpers.PatternParser.extractPrecisionOption(PatternParser.java:116)
	at org.apache.log4j.helpers.PatternParser.finalizeConverter(PatternParser.java:234)
	at org.apache.log4j.helpers.PatternParser.parse(PatternParser.java:186)
	at org.apache.log4j.PatternLayout.setConversionPattern(PatternLayout.java:450)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.log4j.config.PropertySetter.setProperty(PropertySetter.java:245)
	at org.apache.log4j.config.PropertySetter.setProperty(PropertySetter.java:204)
	at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:169)
	at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:104)
	at org.apache.log4j.PropertyConfigurator.parseAppender(PropertyConfigurator.java:805)
	at org.apache.log4j.PropertyConfigurator.parseCategory(PropertyConfigurator.java:768)
	at org.apache.log4j.PropertyConfigurator.configureRootCategory(PropertyConfigurator.java:648)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:514)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:580)
	at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:526)
	at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)
	at org.slf4j.impl.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:66)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:277)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:288)
	at us.codecraft.webmagic.scheduler.DuplicateRemovedScheduler.<init>(DuplicateRemovedScheduler.java:18)
	at us.codecraft.webmagic.scheduler.QueueScheduler.<init>(QueueScheduler.java:19)
	at us.codecraft.webmagic.Spider.<init>(Spider.java:75)
	at us.codecraft.webmagic.Spider.create(Spider.java:119)
	at GithubRepoPageProcessor.main(GithubRepoPageProcessor.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

**Comment by jinyun** [comment]
There is a error in log4j properties,plz close the issue
