### ISSUE TITLE
VPN下使用webmagic下载墙外网站失败

### ISSUE THREAD

**Issue by simplelife-patrick** [code4craft/webmagic#288]
VPN下使用webmagic下载墙外网站失败

VPN环境正常，浏览器可以打开墙外网站，但eclipse下使用webmagic访问则失败：
2016-04-07 11:18:13,102 [us.codecraft.webmagic.Spider]-[INFO] Spider www.pornhub.com started!
2016-04-07 11:18:13,106 [us.codecraft.webmagic.downloader.HttpClientDownloader]-[INFO] downloading page http://www.pornhub.com
2016-04-07 11:18:14,204 [org.apache.http.impl.execchain.RetryExec]-[INFO] I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://210.152.247.121:80: The target server failed to respond
2016-04-07 11:18:14,204 [org.apache.http.impl.execchain.RetryExec]-[INFO] Retrying request to {}->http://210.152.247.121:80
2016-04-07 11:18:14,442 [org.apache.http.impl.execchain.RetryExec]-[INFO] I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://210.152.247.121:80: The target server failed to respond
2016-04-07 11:18:14,443 [org.apache.http.impl.execchain.RetryExec]-[INFO] Retrying request to {}->http://210.152.247.121:80
2016-04-07 11:18:14,680 [org.apache.http.impl.execchain.RetryExec]-[INFO] I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://210.152.247.121:80: The target server failed to respond
2016-04-07 11:18:14,681 [org.apache.http.impl.execchain.RetryExec]-[INFO] Retrying request to {}->http://210.152.247.121:80
2016-04-07 11:18:15,170 [us.codecraft.webmagic.downloader.HttpClientDownloader]-[WARN] download page http://www.pornhub.com error
org.apache.http.NoHttpResponseException: 210.152.247.121:80 failed to respond
    at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:143)
    at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
    at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
    at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:161)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.http.impl.conn.CPoolProxy.invoke(CPoolProxy.java:138)
    at com.sun.proxy.$Proxy0.receiveResponseHeader(Unknown Source)
    at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271)
    at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
    at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:254)
    at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
    at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
    at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
    at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
    at us.codecraft.webmagic.downloader.HttpClientDownloader.download(HttpClientDownloader.java:92)
    at us.codecraft.webmagic.Spider.processRequest(Spider.java:408)
    at us.codecraft.webmagic.Spider$1.run(Spider.java:322)
    at us.codecraft.webmagic.selector.thread.CountableThreadPool$1.run(CountableThreadPool.java:74)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

**Comment by code4craft** [comment]
可能是VPN跟Java环境的问题，你使用简单的URLConnection试一下呢？
