### ISSUE TITLE
java.lang.NoSuchMethodError in webmagic-core-0.5.2.jar

### ISSUE THREAD

**Issue by youyouYoung** [code4craft/webmagic#296]
我尝试了作者在<a href='http://webmagic.io/docs/zh/posts/ch2-install/first-project.html'>WebMagic in Action</a>中介绍的第一个爬虫.

程序出现一下错误:
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.commons.lang3.StringUtils.indexOf(Ljava/lang/CharSequence;Ljava/lang/CharSequence;I)I
	at us.codecraft.webmagic.utils.UrlUtils.getDomain(UrlUtils.java:79)
	at us.codecraft.webmagic.Spider.addRequest(Spider.java:448)
	at us.codecraft.webmagic.Spider.addUrl(Spider.java:473)
	at test.main(test.java:28)

可能的原因:
us.codecraft.webmagic.utils.UrlUtils.getDomain()方法引用了StringUtils.indexOf()方法.
common-lang3.jar, common-lang3-3.1.jar都包含有org.apache.commons.lang3.StringUtils.indexOf()方法,但是common-lang3.jar的方法是indexOf(String s1, String s2, int i)参数类型不匹配.

建议:
us.codecraft.webmagic.utils.UrlUtils类import common-lang3-3.1.jar中的indexOf()

**Comment by code4craft** [comment]
你是clone代码下来跑的吗？
可能是跟你的项目依赖冲突了，WebMagic项目只依赖了common-lang3-3.1，这个依赖是Maven指定的，不是在代码里改的哦。

**Comment by youyouYoung** [comment]
我之前没有使用maven， 现在解决了谢谢
