### ISSUE TITLE
使用RedisScheduler出错，求问

### ISSUE THREAD

**Issue by wangxun155423** [code4craft/webmagic#325]
我使用了RedisScheduler，当日志出现下面异常的时候，控制台经常就会没输出了，程序并没有终止，dump一下看到任务线程都在等待状态，请问这是什么问题啊，碰到过几次了，一直没想出原因？

redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: Read timed out
    at redis.clients.jedis.Protocol.process(Protocol.java:74)
    at redis.clients.jedis.Protocol.read(Protocol.java:122)
    at redis.clients.jedis.Connection.getIntegerReply(Connection.java:178)
    at redis.clients.jedis.Jedis.sismember(Jedis.java:1275)
    at us.codecraft.webmagic.scheduler.RedisScheduler.isDuplicate(RedisScheduler.java:51)
    at us.codecraft.webmagic.scheduler.DuplicateRemovedScheduler.push(DuplicateRemovedScheduler.java:34)
    at us.codecraft.webmagic.Spider.addRequest(Spider.java:453)
    at us.codecraft.webmagic.Spider.extractAndAddRequests(Spider.java:444)
    at us.codecraft.webmagic.Spider.processRequest(Spider.java:422)
    at us.codecraft.webmagic.Spider$1.run(Spider.java:322)
    at us.codecraft.webmagic.thread.CountableThreadPool$1.run(CountableThreadPool.java:74)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.net.SocketTimeoutException: Read timed out
    at java.net.SocketInputStream.socketRead0(Native Method)
    at java.net.SocketInputStream.read(Unknown Source)
    at java.net.SocketInputStream.read(Unknown Source)
    at java.net.SocketInputStream.read(Unknown Source)
    at redis.clients.util.RedisInputStream.fill(RedisInputStream.java:110)
    at redis.clients.util.RedisInputStream.readByte(RedisInputStream.java:46)
    at redis.clients.jedis.Protocol.process(Protocol.java:59)
    ... 13 more

**Comment by wangxun155423** [comment]
几台不同的机器上都有这个错误

**Comment by Leibnizhu** [comment]
看样子是连不上Redis服务器，可以：
1.检查Jedis的服务器和端口设置；
2.看看在本机能否ping通Redis服务器，再用redis-cli尝试连接，发送ping命令测试；
3.登陆Redis的服务器，确认Redis是否开启了。
