### ISSUE TITLE
Xsoup cannot compile valid xpath expression / ()[1] / first element

### ISSUE THREAD

**Issue by timactive** [code4craft/webmagic#339]
I need only the first element for a selector (div[@class="fh-breadcrumb"])[1]. This expression work fine in chrome browser.

`page.getHtml().xpath("//(div[@class=\"fh\\-breadcrumb\"])[1]//li").nodes();`

But when i try  i have this exception linked to Xsoup :

org.jsoup.select.Selector$SelectorParseException: Could not parse query '(div[@class="fh-breadcrumb"])[1]': unexpected token at '(div[@class="fh-breadcrumb"])[1]'
    at us.codecraft.xsoup.xevaluator.XPathParser.findElements(XPathParser.java:166) ~[xsoup-0.3.1.jar:na]
    at us.codecraft.xsoup.xevaluator.XPathParser.parse(XPathParser.java:76) ~[xsoup-0.3.1.jar:na]
    at us.codecraft.xsoup.xevaluator.XPathParser.parse(XPathParser.java:408) ~[xsoup-0.3.1.jar:na]
    at us.codecraft.xsoup.xevaluator.XPathParser.combinator(XPathParser.java:110) ~[xsoup-0.3.1.jar:na]
    at us.codecraft.xsoup.xevaluator.XPathParser.parse(XPathParser.java:74) ~[xsoup-0.3.1.jar:na]
    at us.codecraft.xsoup.xevaluator.XPathParser.parse(XPathParser.java:408) ~[xsoup-0.3.1.jar:na]
    at us.codecraft.xsoup.Xsoup.compile(Xsoup.java:25) ~[xsoup-0.3.1.jar:na]

**Comment by timactive** [comment]
dupplicate with issue https://github.com/code4craft/xsoup/issues/25

**Comment by kenti-lan** [comment]
maybe the xsoup it is implemented by himself.
