### ISSUE TITLE
有些代码没有更新到Maven库中

### ISSUE THREAD

**Issue by ChenJingLei** [code4craft/webmagic#346]
比如commons-lang版本问题，新的版本已经使用3.0版本，但是在Maven库中的代码仍然使用2.6和3.0版本，这将会导致下列错误：
Exception in thread "pool-1-thread-1" java.lang.NoClassDefFoundError: org/apache/commons/lang/StringUtils
    at us.codecraft.webmagic.downloader.HttpClientDownloader.getHtmlCharset(HttpClientDownloader.java:212)
    at us.codecraft.webmagic.downloader.HttpClientDownloader.getContent(HttpClientDownloader.java:194)
    at us.codecraft.webmagic.downloader.HttpClientDownloader.handleResponse(HttpClientDownloader.java:182)
    at us.codecraft.webmagic.downloader.HttpClientDownloader.download(HttpClientDownloader.java:96)
    at us.codecraft.webmagic.Spider.processRequest(Spider.java:409)
    at us.codecraft.webmagic.Spider$1.run(Spider.java:322)
    at us.codecraft.webmagic.thread.CountableThreadPool$1.run(CountableThreadPool.java:74)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang.StringUtils
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 10 more

建议解决方法（2选1）：
1、更新Maven库中的代码
2、说明在App的pom文件中依赖commons-langs2.6版本

**Comment by atumu** [comment]
@ChenJingLei  作者更新较慢, 除了自己编译源码,还有别的办法吗?

**Comment by cranehe** [comment]
同样的问题哈，希望大神推个最新版本到maven中央库 @code4craft

**Comment by code4craft** [comment]
修复commons-langs2.6和commons-langs3.0依赖混乱的问题。
