### ISSUE TITLE
site.setHttpProxyPool(httpProxyList, true)发生数组越界

### ISSUE THREAD

**Issue by hero00ok** [code4craft/webmagic#354]
site.setHttpProxyPool(httpProxyList, true)发生数组越界，代码：
<pre><code> @Override
    public Site getSite() {
        List<String[]> httpProxyList  = new ArrayList<String[]>();
        httpProxyList.add(new String[]{"127.0.0.1","8888"});
        site.setHttpProxyPool(httpProxyList, true);
        return site;
    }</pre></code>
错误内容:
<pre><code>Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 2
    at us.codecraft.webmagic.proxy.SimpleProxyPool.addProxy(SimpleProxyPool.java:159)
    at us.codecraft.webmagic.proxy.SimpleProxyPool.<init>(SimpleProxyPool.java:63)
    at us.codecraft.webmagic.Site.setHttpProxyPool(Site.java:489)
    at us.codecraft.webmagic.processor.example.BaiduBaikePageProcessor.getSite(BaiduBaikePageProcessor.java:39)
    at us.codecraft.webmagic.Spider.<init>(Spider.java:131)
    at us.codecraft.webmagic.Spider.create(Spider.java:121)
    at us.codecraft.webmagic.processor.example.BaiduBaikePageProcessor.main(BaiduBaikePageProcessor.java:45)</pre></code>

**Comment by cpaladin** [comment]
string[]里面需要4个元素，第一个和第二个是用户名和密码，代理认证使用的。第三和第四个才是ip和端口

**Comment by code4craft** [comment]
多谢提醒，文档已改，这个接口设计不太好，后面会重新写一下，新版见  #432。
