### ISSUE TITLE
Read timed out：程序直接结束掉了

### ISSUE THREAD

**Issue by YdjJervis** [code4craft/webmagic#376]
黄老大，请问个问题，同样的这个问题在网上只搜索到一个结果，求助啊！！！我最近一直在用您的框架，谢谢了
[条件]
    1，代码为master最新的；
    2，在抓亚马逊评论翻页的时候，翻着翻着程序就结束了；
[处理方式及结果]
    在报错地方加try catch没用。
[期望]
    知道为什么出现这个问题，知道怎么处理这个问题
java.net.SocketTimeoutException: Read timed out
    at java.net.SocketInputStream.socketRead0(Native Method)
    at java.net.SocketInputStream.read(SocketInputStream.java:152)
    at java.net.SocketInputStream.read(SocketInputStream.java:122)
    at sun.security.ssl.InputRecord.readFully(InputRecord.java:442)
    at sun.security.ssl.InputRecord.read(InputRecord.java:480)
    at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:934)
    at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:891)
    at sun.security.ssl.AppInputStream.read(AppInputStream.java:102)
    at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:139)
    at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:155)
    at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:284)
    at org.apache.http.impl.io.ChunkedInputStream.getChunkSize(ChunkedInputStream.java:266)
    at org.apache.http.impl.io.ChunkedInputStream.nextChunk(ChunkedInputStream.java:227)
    at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:186)
    at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:137)
    at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:238)
    at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
    at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:116)
    at java.io.FilterInputStream.read(FilterInputStream.java:107)
    at org.apache.http.client.entity.LazyDecompressingInputStream.read(LazyDecompressingInputStream.java:67)
    at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1792)
    at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1769)
    at org.apache.commons.io.IOUtils.copy(IOUtils.java:1744)
    at org.apache.commons.io.IOUtils.toByteArray(IOUtils.java:462)
    at **us.codecraft.webmagic.downloader.HttpClientDownloader.getContent(HttpClientDownloader.java:202)
    at us.codecraft.webmagic.downloader.HttpClientDownloader.handleResponse(HttpClientDownloader.java:191)
    at us.codecraft.webmagic.downloader.HttpClientDownloader.download(HttpClientDownloader.java:106)
    at us.codecraft.webmagic.Spider.processRequest(Spider.java:406)
    at us.codecraft.webmagic.Spider$1.run(Spider.java:321)
    at us.codecraft.webmagic.thread.CountableThreadPool$1.run(CountableThreadPool.java:74)**
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

**Comment by dyhack** [comment]
建议把线程和timeout设置的久一点，还有及时使用代理，随时切换

**Comment by code4craft** [comment]
看起来不是最新版本，能否提供个版本？

**Comment by YdjJervis** [comment]
master最新代码

**Comment by code4craft** [comment]
应该是TimeOut之后没有新url就结束了，@dyhack 的建议挺靠谱。这个issue过了这么久才回，估计你问题也解决了，先关闭了。

**Comment by huangminwen** [comment]
我的情况相似，timeout设置成100000了，但是每次还都是只抓取了几页
19-03-30 23:26:37,277 INFO  us.codecraft.webmagic.model.OOSpider(Spider.java:338) ## Spider www.xxxx.con closed! 49 pages downloaded.
