### ISSUE TITLE
webmagic使用的阻塞式HttpClient如何能否防止 socketRead0 hang thread

### ISSUE THREAD

**Issue by njuzhoubing** [code4craft/webmagic#381]
http://stackoverflow.com/questions/28785085/how-to-prevent-hangs-on-socketinputstream-socketread0-in-java

"pool-2141-thread-9" #31346 prio=5 os_prio=0 tid=0x00007f7c71089800 nid=0x6b4e runnable [0x00007f7c1aca6000]
   java.lang.Thread.State: RUNNABLE
    at java.net.SocketInputStream.socketRead0(Native Method)
    at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
    at java.net.SocketInputStream.read(SocketInputStream.java:170)
    at java.net.SocketInputStream.read(SocketInputStream.java:141)
    at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:139)
    at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:155)
    at org.apache.http.impl.io.SessionInputBufferImpl.read(SessionInputBufferImpl.java:208)
    at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:178)
    at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:137)

**Comment by code4craft** [comment]
看起来不能，也没有模拟过这么高请求量的场景，有什么建议吗？
