### ISSUE TITLE
请问使用注解的方式如何抓取指定列表页下的文章？

### ISSUE THREAD

**Issue by zifangsky** [code4craft/webmagic#402]
如题，也就是这篇文章说到的这个问题：http://webmagic.io/docs/zh/posts/chx-cases/basic-list-target.html
但是使用注解的话，怎么来区分啊？
大家有什么比较好的解决方法吗？希望能够分享一下，谢谢！

**Comment by jsbd** [comment]
@zifangsky 我这里有一个基于注解的例子，不知道是否是你需要的，供你参考一下
`import us.codecraft.webmagic.Site;
import us.codecraft.webmagic.model.ConsolePageModelPipeline;
import us.codecraft.webmagic.model.OOSpider;
import us.codecraft.webmagic.model.annotation.ExtractBy;
import us.codecraft.webmagic.model.annotation.ExtractBy.Source;
import us.codecraft.webmagic.model.annotation.TargetUrl;

@TargetUrl("http://www.uedbox.com/2016-ali-security-summit-information/")
@ExtractBy(value = "//div[@class='blog_a_con']/ul/li/a", multi = true, source = Source.SelectedHtml)
public class AliyunSpider {

  @ExtractBy("//a/text()")
  private String bookName;

  @ExtractBy("//a/@href")
  private String downloadUrl;

  public static void main(String[] args) {
    OOSpider.create(Site.me().setCharset("UTF-8"), new ConsolePageModelPipeline(), AliyunSpider.class)
        .addUrl("http://www.uedbox.com/2016-ali-security-summit-information/").run();
  }

  public String getBookName() {
    return bookName;
  }

  public void setBookName(String bookName) {
    this.bookName = bookName;
  }

  public String getDownloadUrl() {
    return downloadUrl;
  }

  public void setDownloadUrl(String downloadUrl) {
    this.downloadUrl = downloadUrl;
  }

}`

**Comment by lcbbcl** [comment]
之前也考虑过用注解，但是如果页面解析有比较复杂的业务处理的话，楼主考虑一下不用注解会比较容易

**Comment by zifangsky** [comment]
@lcbbcl 的确，页面逻辑比较复杂的情况还是手动判断好处理一点

**Comment by krisshen** [comment]
@zifangsky 目前有一种方法可行，就是爬2次，第一次先把主页里面的分页链接抓下来，然后当作参数传给第二次要爬取的URL列表就好，这种方式感觉不太好的但是可行。

还有一种方法没有测试成功，看了源码，觉得理论上可行，可以试一下。在@HelpUrl里面使用正则表达式把分页链接的逻辑放进去，使得HelpUrl能覆盖主页和分页的URL，这样ModelPageProcessor就会根据你提供的正则表达式的规则把主页和分页URL都放到TargetRequest里去爬取。

**Comment by krisshen** [comment]
第二种方法测试成功，果然是我正则表达式有问题。。。

首先在OOSpider.addUrl()里面只放入要爬的主页就好，然后只把分页的正则表达式逻辑放在@HelpUrl里面，这样基本就好了。@TargetUrl里面始终是那个具体的要抓信息的页面URL的正则表达式。

在我测试的网站分页链接里面的参数顺序是随机的，正则表达式不会写这个随机逻辑。。。
所以@HelpUrl里面的分页正则表达式去掉了所有的URL参数，只留下了一段URL去匹配，再用sourceRegion限定一下范围就好了，这样简单粗暴。

**Comment by jsbd** [comment]
@krisshen ＋1

**Comment by gam2046** [comment]
我这样的代码:
```java
@TargetUrl("https://www.v2ex.com/go/*")
@ExtractBy(value = "//div[@id='TopicsNode']/div/table[@border=0]", multi = true)
public class ForumBean extends BasicBean {
    @ExtractBy("//span[@class='item_title']/a/@href")
    private String forumUrl;
    @ExtractBy("//span[@class='item_title']/a/text()")
    private String forumTitle;
    @ExtractBy("//img[@class='avatar']/@src")
    private String posterAvatar;
    @ExtractBy("//a[@class='count_livid']/text()")
    private int recCount;

    // getter and setter
}
```

```java
        OOSpider.create(Site.me(),new ConsolePageModelPipeline(), ForumBean.class)
                .addUrl("https://www.v2ex.com/go/programmer").run();
```

跑起来以后，就会自己翻页爬下一页。然而我并不希望他自动翻页。

**Comment by zifangsky** [comment]
@krisshen 但是现在关键问题在于我使用“sourceRegion”这个参数的时候代码就爆下面这个错误：
`17-01-05 10:55:05,537 ERROR us.codecraft.webmagic.model.OOSpider(Spider.java:326) ## process request Request{url='https://www.zifangsky.cn/life/read', method='null', extras={statusCode=200}, priority=0} error
java.lang.UnsupportedOperationException
	at us.codecraft.webmagic.selector.PlainText.links(PlainText.java:52)
	at us.codecraft.webmagic.model.ModelPageProcessor.extractLinks(ModelPageProcessor.java:67)
	at us.codecraft.webmagic.model.ModelPageProcessor.process(ModelPageProcessor.java:49)
	at us.codecraft.webmagic.Spider.processRequest(Spider.java:420)
	at us.codecraft.webmagic.Spider$1.run(Spider.java:322)
	at us.codecraft.webmagic.selector.thread.CountableThreadPool$1.run(CountableThreadPool.java:74)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)`
这是我的测试案例：
`@TargetUrl(value="https://www.zifangsky.cn/\\d+.html",sourceRegion="//section[@id='main']/outerHtml()")
@HelpUrl(value="https://www.zifangsky.cn/life/read(/page/\\d*)?")
public class ArticleExtra{
	/**
	 * 标题
	 */
	@ExtractBy(value="//h1[@class='entry-title']/tidyText()",notNull=true)
	private String title;
	/**
	 * 作者
	 */
	@ExtractBy("//span[@class='fa fa-user']/a/text()")
	private String author;
	
	/**
	 * 文章URL
	 */
	@ExtractByUrl("https://www.zifangsky.cn/\\d+.html")
	private String url;
	
	/**
	 * 文章标签
	 */
	@ExtractBy(value="//div[@class='footer-tag clearfix']/div/a/text()",multi=true)
	private List<String> tags;
	
	/**
	 * 文章正文
	 * @return
	 */
	@ExtractBy("//div[@class='entry-content clearfix']/tidyText()")
	private String content;
（略）
}
`
我看到官方文档中有说到可以用sourceRegion来限定范围啊：

> TargetUrl还支持定义sourceRegion，这个参数是一个XPath表达式，指定了这个URL从哪里得到——不在sourceRegion的URL不会被抽取。

有点搞不明白是我的代码的问题还是别的什么的问题

**Comment by krisshen** [comment]
@zifangsky 不好意思回复晚了。。。
不知你解决这个问题没有，我刚试了下你的代码，发现把sourceRegion里面的outerHtml去掉就好了，就像下面这样：
@TargetUrl(value = "https://www.zifangsky.cn/\\d+.html", sourceRegion = "//*[@id=\"main\"]")

http://webmagic.io/docs/zh/posts/ch4-basic-page-processor/xsoup.html 这里面说outerHtml是自定义的XPath方法，但是sourceRegion这里显然并不支持。

**Comment by krisshen** [comment]
@gam2046 
我觉得是因为你的@TargetUrl("https://www.v2ex.com/go/*****")里面被抓页面的URL和当前页面里面那些分页链接的URL都会被“https://www.v2ex.com/go/*”匹配到，所以它会一直递归的抓下去。。。
你想抓到当前页面：https://www.v2ex.com/go/**programmer**
当前页面里面所有的翻页链接：https://www.v2ex.com/go/**programmer?p=1**

如果你不想翻页就把TargetUrl里面写死就好了，不要用正则去匹配。

**Comment by zifangsky** [comment]
@krisshen 多谢回复，我再试试看
