### ISSUE TITLE
第一个项目运行报错，com.google.common.collect.Table

### ISSUE THREAD

**Issue by le0zh0u** [code4craft/webmagic#416]
我自己建了一个项目，
导入了
<dependency>
			<groupId>us.codecraft</groupId>
			<artifactId>webmagic-core</artifactId>
			<version>0.5.3</version>
		</dependency>
		<dependency>
			<groupId>us.codecraft</groupId>
			<artifactId>webmagic-extension</artifactId>
			<version>0.5.3</version>
		</dependency>
运行之后报
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/collect/Table
at com.leozhou.webmagic.GithubRepoPageProcessor.(GithubRepoPageProcessor.java:14)
at com.leozhou.webmagic.GithubRepoPageProcessor.main(GithubRepoPageProcessor.java:39)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.Table
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 7 more

**Comment by Strong-it** [comment]
你是在AS运行的时候报错？ 我也同样遇到，感觉直接要放弃了

**Comment by code4craft** [comment]
可能是Guava版本问题导致的，能提供以下你的Guava版本吗？

**Comment by Strong-it** [comment]
是在AS 2.1上运行的， JDK是1.8，导入了核心和扩展2个.jar包，并没有Guava的相关操作，可以告知怎么查看吗？

**Comment by code4craft** [comment]
AS是什么，我觉得我是不是落伍了？

**Comment by le0zh0u** [comment]
@Strong-it 我也不知道AS是什么的，我在IDEA上跑的，问题是有一个Guava的包没有导入，因为是google的包，应该是国内的问题，没有下载下来，所以报错了，手动下载并导入就可以了，只是跑起来之后，连接github显示连接超时😂。 @code4craft 是包的问题，也可能是和网络有关系。Guava需要手动导入。

**Comment by le0zh0u** [comment]
01:00:09.013 [pool-1-thread-1] WARN us.codecraft.webmagic.downloader.HttpClientDownloader - download page https://github.com/code4craft error
org.apache.http.conn.ConnectTimeoutException: Connect to github.com:443 [github.com/192.30.253.112, github.com/192.30.253.113] failed: connect timed out
这是什么问题额。不懂为什么在github.com后面跟有ip @code4craft 请问下，你之前有碰到过这个问题吗

**Comment by code4craft** [comment]
@le0zh0u 这个是github访问太慢，没别的原因…

**Comment by code4craft** [comment]
@Strong-it 过两天可以试试0.6.0，Guava的依赖去掉了。

**Comment by le0zh0u** [comment]
好吧。。只是没有理解在网址后面跟了ip，😂

**Comment by Strong-it** [comment]
AS = Android Studio， 期待新版本
