### ISSUE TITLE
Spring boot， mybatis，Redis Scheduler一起使用时出错

### ISSUE THREAD

**Issue by Xinghan** [code4craft/webmagic#422]
版本用的是0.5.3，并且尝试了自己编译源码，还是一样的错误。
在创建redisscheduler时候会报以下错误：
java.lang.NoClassDefFoundError: org/apache/commons/pool/impl/GenericObjectPool$Config
	at com.scientistin.spider.BaiduPaperSpider.crawl(BaiduPaperSpider.java:50)
	at com.scientistin.SinspiderApplication.run(SinspiderApplication.java:37)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:800)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:784)
	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:771)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175)
	at com.scientistin.SinspiderApplication.main(SinspiderApplication.java:32)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.pool.impl.GenericObjectPool$Config
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 9 common frames omitted

Jedis 使用了commons.pool2，不知道哪里冲突了

spring boot版本：1.4.2.RELEASE
mybatis版本：mybatis-spring-boot-starter：1.1.1

**Comment by code4craft** [comment]
看起来是Jedis依赖的commons.pool导致的，升级到2.9.0重新编译一下试试？

**Comment by code4craft** [comment]
没有反馈，暂时关闭此issue了。

**Comment by feverbit** [comment]
我也遇到一样的问题。找到原因如下：
1.webmagic 0.5.3使用了 jedis 2.0.0，jedis2.0.0使用了commons.pool；现在一般工程引入的jedis都在2.8.1 或者2.9.0以上，是使用了commons.pool2，而pool和pool2是完全不兼容的。

2.我在POM.xml显式指定webmagic exclusion jedis，然后在外部引入jedis2.9.0，还是无法改变，原因可能是我引入webmagic是war的方式，优先级更高。

3.我把redis降级到2.0.0，可以用了，不过目前的redisschedule在run的一开始就pop 队列，不管后面是否抓成功，都会在已抓取队列里面（事实上用了代理出现500，403，404的情况非常多）。所以redisschedule没法满足我的需求，事实上，我对run的开始就pop队列这个逻辑存疑，感觉并不符合大多数实战场景，毕竟不开代理去抓取的场景只能是很学术很peaceful的吧：）。所以目前采用了AOP切面，强制在run的开始手动控制redis来做缓存。
