### ISSUE TITLE
注解中使用JsonPath报错

### ISSUE THREAD

**Issue by billho** [code4craft/webmagic#462]
在@ExtractBy注解中使用JsonPath，报错：

```
Exception in thread "main" java.lang.NoSuchMethodError: com.jayway.jsonpath.JsonPath.compile(Ljava/lang/String;[Lcom/jayway/jsonpath/Filter;)Lcom/jayway/jsonpath/JsonPath;
	at us.codecraft.webmagic.selector.JsonPathSelector.<init>(JsonPathSelector.java:23)
	at us.codecraft.webmagic.utils.ExtractorUtils.getSelector(ExtractorUtils.java:31)
	at us.codecraft.webmagic.model.PageModelExtractor.getAnnotationExtractBy(PageModelExtractor.java:181)
	at us.codecraft.webmagic.model.PageModelExtractor.init(PageModelExtractor.java:59)
	at us.codecraft.webmagic.model.PageModelExtractor.create(PageModelExtractor.java:49)
	at us.codecraft.webmagic.model.ModelPageProcessor.addPageModel(ModelPageProcessor.java:36)
	at us.codecraft.webmagic.model.ModelPageProcessor.create(ModelPageProcessor.java:29)
	at us.codecraft.webmagic.model.OOSpider.<init>(OOSpider.java:68)
	at us.codecraft.webmagic.model.OOSpider.create(OOSpider.java:85)
	at cn.billho.crawlexam.TermOnLineCrawl.main(TermOnLineCrawl.java:22)
```

跟了一下，发现抓取下来的Json，自动被加上了`<head></head><body></body>` 包裹着。
这应该是个Bug吧？
有什么方法解决？

源代码如下：

```
public class TermOnLineCrawl {
	
	@ExtractBy(value="$",type=ExtractBy.Type.JsonPath)
	//@ExtractBy(value="body/text()")
	String term;
	
	public static void main(String[] args) {
		String url = "http://www.termonline.cn/list.jhtm?op=query&k=Ecotoxicology&start=0&pageSize=15&sort=&resultType=0&conds%5B0%5D.key=all&conds%5B0%5D.match=1&conds%5B1%5D.val=&conds%5B1%5D.key=category&conds%5B1%5D.match=1&conds%5B2%5D.val=&conds%5B2%5D.key=subject_code&conds%5B2%5D.match=3&conds%5B3%5D.val=&conds%5B3%5D.key=publish_year&conds%5B3%5D.match=1&conds%5B0%5D.val=";
		//log.info("start...");
        OOSpider.create(Site.me().addStartUrl(url + "Ecotoxicology")
        		
        		.addHeader("Accept", "application/json")
        		.addHeader("User-Agent", "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36")
        		, TermOnLineCrawl.class)
        
        .addPipeline(new ConsolePipeline()).run();
    }
	
	public String toString(){
		return term;
	}
}
```

**Comment by code4craft** [comment]
是bug，之前默认会走Jsoup过一遍，这边需要重构一下。

**Comment by billho** [comment]
OK！什么时候能fix？

**Comment by old-king** [comment]
```java
List<String> ids = new JsonPathSelector("$.data[*]._id").selectList(page.getRawText());
            if (CollectionUtils.isNotEmpty(ids)) {
                for (String id : ids) {
                    LOGGER.info("''''''''''''''''''''''" + id + "''''''''''''''''''''''''");
                }
            }
```
这样使用也报错误，请问该如何解决？
```java
Exception in thread "pool-2-thread-1" java.lang.NoSuchMethodError: com.jayway.jsonpath.JsonPath.compile(Ljava/lang/String;[Lcom/jayway/jsonpath/Filter;)Lcom/jayway/jsonpath/JsonPath;
	at us.codecraft.webmagic.selector.JsonPathSelector.<init>(JsonPathSelector.java:23)
	at com.sensefun.gather.crawl.pageprocessor.sporttery.FootballPageProcessor.process(FootballPageProcessor.java:28)
	at us.codecraft.webmagic.Spider.processRequest(Spider.java:416)
	at us.codecraft.webmagic.Spider$1.run(Spider.java:321)
	at us.codecraft.webmagic.thread.CountableThreadPool$1.run(CountableThreadPool.java:74)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by code4craft** [comment]
看了一下，`java.lang.NoSuchMethodError`是依赖问题，决定还是将jsonpath升级一下吧。

**Comment by code4craft** [comment]
已改进，见 #589 。
