### ISSUE TITLE
java.io.UnsupportedEncodingException: gbk2312

### ISSUE THREAD

**Issue by AaricChen** [code4craft/webmagic#463]
It's very nice tool, and easy to use :)

but got one Exception when download some webpages.

```
java.io.UnsupportedEncodingException: gbk2312
        at java.lang.StringCoding.decode(StringCoding.java:190) ~[na:1.8.0_91]
        at java.lang.String.<init>(String.java:426) ~[na:1.8.0_91]
        at java.lang.String.<init>(String.java:491) ~[na:1.8.0_91]
        at us.codecraft.webmagic.downloader.HttpClientDownloader.getContent(HttpClientDownloader.java:205) ~[webmagic-core-0.6.1.jar!/:na]
        at us.codecraft.webmagic.downloader.HttpClientDownloader.handleResponse(HttpClientDownloader.java:191) ~[webmagic-core-0.6.1.jar!/:na]
        at us.codecraft.webmagic.downloader.HttpClientDownloader.download(HttpClientDownloader.java:106) ~[webmagic-core-0.6.1.jar!/:na]
        at us.codecraft.webmagic.Spider.processRequest(Spider.java:404) [webmagic-core-0.6.1.jar!/:na]
        at us.codecraft.webmagic.Spider$1.run(Spider.java:321) [webmagic-core-0.6.1.jar!/:na]
        at us.codecraft.webmagic.thread.CountableThreadPool$1.run(CountableThreadPool.java:74) [webmagic-core-0.6.1.jar!/:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_91]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]
```

Could you help with this? thanks in advance. :)

**Comment by jsbd** [comment]
字符集编码应该是GBK or GB2312吧，改一下试试看

**Comment by AaricChen** [comment]
这里是抓取的别的站点，应该是他们设置的字符集对吧？  我这边是不是修改不了

**Comment by AaricChen** [comment]
另外问题已经解决了，把jre\lib\charset.jar 加到classpath就可以了。 谢谢
