### ISSUE TITLE
抓取ajax渲染的页面，利用jsonPath报错，求解决方式！！！

### ISSUE THREAD

**Issue by dpjs** [code4craft/webmagic#477]
Exception in thread "pool-1-thread-1" java.lang.NoSuchMethodError: com.jayway.jsonpath.JsonPath.compile(Ljava/lang/String;[Lcom/jayway/jsonpath/Filter;)Lcom/jayway/jsonpath/JsonPath;

**Comment by code4craft** [comment]
请问下你是不是用了其他版本的JsonPath? WebMagic用的JsonPath版本比较老(`0.8.1`)，可以用`mvn dependency:tree`看一下依赖版本。我这边测试是没问题的。

**Comment by dpjs** [comment]
用的2.2.0版本的

**Comment by code4craft** [comment]
2.2.0版本目前是不支持的，它有些行为跟之前设想的不一样…建议换到0.8.1试一下。

**Comment by old-king** [comment]
webmagic-core（0.6.1） 默认的使用就是JsonPath（2.2.0）。。。

**Comment by pluone** [comment]
我也发现了这个问题，我的项目使用的是0.5.3,这个项目的json-path的依赖版本是2.2.0,经过分析是你们**项目maven仓库中的jar包有错误**

调用的伪代码如下：
```
class FooProcessor implements PageProcessor {
     @Override
     public void process(Page page) {
           Json json = page.getJson();
           json.jsonPath("$.json_path");//这一行代码报错
    }
}
```
错误信息如下:
```
Exception in thread "pool-1-thread-1" java.lang.NoSuchMethodError: com.jayway.jsonpath.JsonPath.compile(Ljava/lang/String;[Lcom/jayway/jsonpath/Filter;)Lcom/jayway/jsonpath/JsonPath;
	at us.codecraft.webmagic.selector.JsonPathSelector.<init>(JsonPathSelector.java:23)
	at us.codecraft.webmagic.selector.Json.jsonPath(Json.java:54)
```

我是用classpy（一款字节码查看工具）查看了us.codecraft.webmagic.selector.JsonPathSelector.class发现class文件中调用`JsonPath.compile(this.jsonPathStr);`的字节码是`com.jayway.jsonpath.JsonPath.compile(Ljava/lang/String;[Lcom/jayway/jsonpath/Filter;)Lcom/jayway/jsonpath/JsonPath;` 
而JsonPah.compile方法签名的字节码是`com.jayway.jsonpath.JsonPath.compile(Ljava/lang/String;[Lcom/jayway/jsonpath/Predicate;)Lcom/jayway/jsonpath/JsonPath;`,这两个签名中第二个参数的类型是不一致的,显然JsonPathSelector里的生成的字节码类型是错误的

`mvn dependency:tree | grep jsonpath -C 10`查看json-path版本号
```
[INFO] +- us.codecraft:webmagic-core:jar:0.5.3:compile
[INFO] |  +- com.google.guava:guava:jar:18.0:compile
[INFO] |  +- us.codecraft:xsoup:jar:0.3.1:compile
[INFO] |  |  \- org.assertj:assertj-core:jar:2.5.0:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.21:compile
[INFO] |  +- org.slf4j:slf4j-log4j12:jar:1.7.21:compile
[INFO] |  |  \- log4j:log4j:jar:1.2.17:compile
[INFO] |  +- commons-collections:commons-collections:jar:3.2.2:compile
[INFO] |  +- org.jsoup:jsoup:jar:1.8.3:compile
[INFO] |  +- com.jayway.jsonpath:json-path:jar:2.2.0:compile
[INFO] |  |  \- net.minidev:json-smart:jar:2.2.1:compile
[INFO] |  |     \- net.minidev:accessors-smart:jar:1.1:compile
[INFO] |  |        \- org.ow2.asm:asm:jar:5.0.3:compile
[INFO] |  \- com.alibaba:fastjson:jar:1.1.37:compile
[INFO] +- us.codecraft:webmagic-extension:jar:0.5.3:compile
```

**Comment by TonyZhang1002** [comment]
可以查看这个 [#589](https://github.com/code4craft/webmagic/issues/589) 手动指定json-path版本可以解决问题
