### ISSUE TITLE
使用RedisSchedule遇到Redis time out的Exception导致爬虫hang住

### ISSUE THREAD

**Issue by ncistyang** [code4craft/webmagic#547]
使用RedisSchedule遇到Redis time out的Exception导致爬虫hang住，此时爬虫无法继续爬取也没有停止。错误堆栈如下

Exception in thread "Thread-3" redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: Read timed out
	at redis.clients.jedis.Protocol.process(Protocol.java:74)
	at redis.clients.jedis.Protocol.read(Protocol.java:122)
	at redis.clients.jedis.Connection.getBinaryBulkReply(Connection.java:172)
	at redis.clients.jedis.Connection.getBulkReply(Connection.java:161)
	at redis.clients.jedis.Jedis.lpop(Jedis.java:1099)
	at us.codecraft.webmagic.scheduler.RedisScheduler.poll(RedisScheduler.java:81)
	at us.codecraft.webmagic.Spider.run(Spider.java:309)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(SocketInputStream.java:152)
	at java.net.SocketInputStream.read(SocketInputStream.java:122)
	at java.net.SocketInputStream.read(SocketInputStream.java:108)
	at redis.clients.util.RedisInputStream.fill(RedisInputStream.java:110)
	at redis.clients.util.RedisInputStream.readByte(RedisInputStream.java:46)
	at redis.clients.jedis.Protocol.process(Protocol.java:59)
	... 7 more

**Comment by code4craft** [comment]
这里看起来不会导致hang住，最好结合jstack看一下到底阻塞在哪里。
