### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by kaikai7654321** [code4craft/webmagic#550]
java.net.UnknownHostException: sdpyqtl.cn.china.cn
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(Unknown Source)
爬一个网站，但是时不时的就报这个错误（下面还有很长，），
和webmagic有关的是：
at us.codecraft.webmagic.downloader.HttpClientDownloader.download(HttpClientDownloader.java:102)
	at us.codecraft.webmagic.Spider.processRequest(Spider.java:404)
	at us.codecraft.webmagic.Spider$1.run(Spider.java:321)
	at us.codecraft.webmagic.thread.CountableThreadPool$1.run(CountableThreadPool.java:74)
有那位大神知道为什么吗

**Comment by code4craft** [comment]
这个是域名解析错误，跟爬虫无关，看起来是IPv6解析错误，应该也不会有影响。
