### ISSUE TITLE
java.lang.NoSuchMethodError: org.apache.commons.collections.CollectionUtils.isNotEmpty(Ljava/util/Collection;)Z

### ISSUE THREAD

**Issue by wmjdmin** [code4craft/webmagic#621]
从 page 对象获取json 时发生异常
代码如下：

`    @org.junit.Test
    public void saveHotSinger() {
        Spider.create(new HotSingerPage())
                .addUrl("http://127.0.0.1:3000/top/artists?offset=0&limit=100")
                .run();
    }`

`@Override
    public void process(Page page) {
        Json json = page.getJson();
        List<Object> objects = json.toList(Object.class);
        int i = 0;
    }`

异常信息：

Exception in thread "pool-1-thread-1" java.lang.NoSuchMethodError: org.apache.commons.collections.CollectionUtils.isNotEmpty(Ljava/util/Collection;)Z
	at us.codecraft.webmagic.Spider.onError(Spider.java:342)
	at us.codecraft.webmagic.Spider$1.run(Spider.java:323)
	at us.codecraft.webmagic.thread.CountableThreadPool$1.run(CountableThreadPool.java:74)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Disconnected from the target VM, address: '127.0.0.1:33647', transport: 'socket'

**Comment by luchatex** [comment]
建议使用page.getRawText试试,看看传过来的json是否规范,再使用fastjson解析.

**Comment by code4craft** [comment]
java.lang.NoSuchMethodError，看看依赖的common-collections是什么版本？

**Comment by wmjdmin** [comment]
@code4craft @luchatex 可能是因为我的项目里 common-collections 版本低了，看到 webmagic 依赖的是3.2.2
