### ISSUE TITLE
使用代理爬取https页面失败

### ISSUE THREAD

**Issue by orlandotian** [code4craft/webmagic#642]
使用代理爬取http页面没问题，不使用代码爬取https页面没问题。
但是使用代码爬取https页面就不可以了，看描述应该是apache http版本的问题

org.apache.http.NoHttpResponseException: benxi.anjuke.com:443 failed to respond
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:143)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
	at org.apache.http.impl.execchain.MainClientExec.createTunnelToTarget(MainClientExec.java:472)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:397)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at us.codecraft.webmagic.downloader.HttpClientDownloader.download(HttpClientDownloader.java:85)

**Comment by JPCui** [comment]
@orlandotian 日志信息有点不全，我遇到的问题有：
1. 代理服务器的问题
2. METHOD NOT SUPPORT，猜想：
> 我从日志看到有些代理的 request method 是 CONNECT，但是目标服务器并不支持（根据错误日志猜想），其实根本原因还不知道

我是直接爬取网上的代理来用的，欢迎交流~

**Comment by go2run** [comment]
楼主这个解决了吗？我也遇到一个类似的报错，也是https
