### ISSUE TITLE
java.io.UnsupportedEncodingException: gb2312 gbk utf-8 UTF-8 Big5

### ISSUE THREAD

**Issue by chen1457789** [code4craft/webmagic#680]
使用默认下载器，某些网站（如http://www.bfnews.com.cn）出现
`
java.io.UnsupportedEncodingException: gb2312 gbk utf-8 UTF-8 Big5
	at java.base/java.lang.StringCoding.decode(StringCoding.java:260)
	at java.base/java.lang.String.<init>(String.java:465)
	at java.base/java.lang.String.<init>(String.java:535)
	at us.codecraft.webmagic.downloader.HttpClientDownloader.handleResponse(HttpClientDownloader.java:120)
	at us.codecraft.webmagic.downloader.HttpClientDownloader.download(HttpClientDownloader.java:86)
	at us.codecraft.webmagic.Spider.processRequest(Spider.java:404)
	at us.codecraft.webmagic.Spider.access$000(Spider.java:61)
	at us.codecraft.webmagic.Spider$1.run(Spider.java:320)
	at us.codecraft.webmagic.thread.CountableThreadPool$1.run(CountableThreadPool.java:74)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)
`

**Comment by zhanghuihb** [comment]
今天给遇到相同问题
Caused by: org.apache.http.HttpException: Unsupported Content-Coding: UTF-8
	at org.apache.http.client.protocol.ResponseContentEncoding.process(ResponseContentEncoding.java:130)
	at org.apache.http.protocol.ImmutableHttpProcessor.process(ImmutableHttpProcessor.java:141)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:189)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	... 9 more

其他页面返回的Content-Encoding:gzip,     看了源码，仅仅支持四种，不包含utf-8,所以报此异常。

但是返回头里面  
Accept-Ranges:bytes
Access-Control-Allow-Origin:*
Cache-Control:no-cache
Connection:keep-alive
Content-Encoding:UTF-8
Content-Type:text/html;charset=utf-8
Date:Fri, 01 Jun 2018 06:47:11 GMT
ETag:"ccb11bbc21e9a9de7e61f4a4536f8977"
Keep-Alive:timeout=5
Last-Modified:Thu, 31 May 2018 22:52:38 GMT
Pragma:no-cache
Server:DPweb

返回的时utf-8 

楼主解决了么？
