### ISSUE TITLE
用webmagic爬取的过程中时常会出现这个错误：Read timed out，求问如何解决，把timeout时间设置长点影响反应速度，还有什么其他方法？

### ISSUE THREAD

**Issue by 1BOB** [code4craft/webmagic#686]
17-11-07 15:47:27,307 WARN  us.codecraft.webmagic.downloader.HttpClientDownloader(HttpClientDownloader.java:91) ## download page  https://www.amazon.com/s/ref=nb_sb_noss?field-keywords=wifi 

 extender error
java.net 

.SocketTimeoutException: Read timed out
	at java.net 

.SocketInputStream.socketRead0(Native Method)
	at java.net 

.SocketInputStream.socketRead(Unknown Source)
	at java.net 

.SocketInputStream.read(Unknown Source)
	at java.net 

.SocketInputStream.read(Unknown Source)
	at sun.security.ssl.InputRecord.readFully(Unknown Source)
	at sun.security.ssl.InputRecord.readV3Record(Unknown Source)
	at sun.security.ssl.InputRecord.read(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(Unknown Source)
	at sun.security.ssl.AppInputStream.read(Unknown Source)
	at org.apache.http.impl.io 

.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:139)
	at org.apache.http.impl.io 

.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:155)
	at org.apache.http.impl.io 

.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:284)
	at org.apache.http.impl.io 

.ChunkedInputStream.getChunkSize(ChunkedInputStream.java:266)
	at org.apache.http.impl.io 

.ChunkedInputStream.nextChunk(ChunkedInputStream.java:227)
	at org.apache.http.impl.io 

.ChunkedInputStream.read(ChunkedInputStream.java:186)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:137)
	at java.util.zip.InflaterInputStream.fill(Unknown Source)
	at java.util.zip.InflaterInputStream.read(Unknown Source)
	at java.util.zip.GZIPInputStream.read(Unknown Source)
	at java.io 

.FilterInputStream.read(Unknown Source)
	at org.apache.http.client.entity.LazyDecompressingInputStream.read(LazyDecompressingInputStream.java:67)
	at org.apache.commons.io 

.IOUtils.copyLarge(IOUtils.java:1025)
	at org.apache.commons.io 

.IOUtils.copy(IOUtils.java:999)
	at org.apache.commons.io 

.IOUtils.toByteArray(IOUtils.java:218)
	at us.codecraft.webmagic.downloader.HttpClientDownloader.handleResponse(HttpClientDownloader.java:111)
	at us.codecraft.webmagic.downloader.HttpClientDownloader.download(HttpClientDownloader.java:86)
	at us.codecraft.webmagic.Spider.processRequest(Spider.java:411)
	at us.codecraft.webmagic.Spider.access$2(Spider.java:410)
	at us.codecraft.webmagic.Spider$1.run(Spider.java:327)
	at us.codecraft.webmagic.thread.CountableThreadPool$1.run(CountableThreadPool.java:74)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by Nightmareone** [comment]
我也遇到这个问题....反应速度也调的很大了，而且就算是单线程也会出现这种情况

**Comment by HowieChih** [comment]
这个是网络问题导致的吧，挂代理试试。

**Comment by 1BOB** [comment]
有什么好的代理推荐吗？我挂了代理还没我电脑爬的快

**Comment by xieahui** [comment]
貌似设置重试次数没怎么起作用
