### ISSUE TITLE
 CircularRedirectException: Circular redirect to

### ISSUE THREAD

**Issue by jqsl2012** [code4craft/webmagic#728]
`08:15:43.817 [main] INFO  us.codecraft.webmagic.Spider - Spider ask.csdn.net started!
08:15:43.818 [pool-1-thread-1] INFO  u.c.w.d.HttpClientDownloader - downloading page http://ask.csdn.net/questions?type=resolved
08:15:43.958 [pool-1-thread-1] WARN  u.c.w.d.HttpClientDownloader - download page http://ask.csdn.net/questions?type=resolved error
org.apache.http.client.ClientProtocolException: null
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:187)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at us.codecraft.webmagic.downloader.HttpClientDownloader.download(HttpClientDownloader.java:102)
	at us.codecraft.webmagic.Spider.processRequest(Spider.java:404)
	at us.codecraft.webmagic.Spider$1.run(Spider.java:321)
	at us.codecraft.webmagic.thread.CountableThreadPool$1.run(CountableThreadPool.java:74)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.http.client.CircularRedirectException: Circular redirect to 'http://ask.csdn.net/questions?type=resolved'
	at org.apache.http.impl.client.DefaultRedirectStrategy.getLocationURI(DefaultRedirectStrategy.java:177)
	at us.codecraft.webmagic.downloader.CustomRedirectStrategy.getRedirect(CustomRedirectStrategy.java:28)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:122)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	... 9 common frames omitted`

**Comment by jqsl2012** [comment]
不好意思，管理员可以关闭了，header没设置对。。
