### ISSUE TITLE
获取网页内容，Response Headers  中 Content-Encoding:UTF-8 报Unsupported Content-Coding: UTF-8

### ISSUE THREAD

**Issue by zhanghuihb** [code4craft/webmagic#796]
org.apache.http.client.ClientProtocolException
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at us.codecraft.webmagic.downloader.HttpClientDownloader.download(HttpClientDownloader.java:85)
	at us.codecraft.webmagic.Spider.processRequest(Spider.java:404)
	at us.codecraft.webmagic.Spider.access$000(Spider.java:61)
	at us.codecraft.webmagic.Spider$1.run(Spider.java:320)
	at us.codecraft.webmagic.thread.CountableThreadPool$1.run(CountableThreadPool.java:74)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.http.HttpException: Unsupported Content-Coding: UTF-8
	at org.apache.http.client.protocol.ResponseContentEncoding.process(ResponseContentEncoding.java:130)
	at org.apache.http.protocol.ImmutableHttpProcessor.process(ImmutableHttpProcessor.java:141)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:189)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	... 9 more

ResponseHeaders头中的返回结果
Accept-Ranges:bytes
Access-Control-Allow-Origin:*
Cache-Control:no-cache
Connection:keep-alive
Content-Encoding:UTF-8
Content-Type:text/html;charset=utf-8
Date:Fri, 01 Jun 2018 06:47:11 GMT
ETag:"ccb11bbc21e9a9de7e61f4a4536f8977"
Keep-Alive:timeout=5
Last-Modified:Thu, 31 May 2018 22:52:38 GMT
Pragma:no-cache
Server:DPweb

.register("gzip", GZIP)
 .register("x-gzip", GZIP)
 .register("deflate", DEFLATE)
!"identity".equals(codecname)

只支持者四种，utf-8怎么处理

**Comment by ChinLong** [comment]
```java
Site.me().setCharset("UTF-8")
```
 这个设置了吗？
