### ISSUE TITLE
java.lang.ClassNotFoundException: us.codecraft.webmagic.processor.Pag eProcessor

### ISSUE THREAD

**Issue by thikill** [code4craft/webmagic#806]
C:\myrepos\water-crawl\target>java -jar water-crawl-0.0.1-SNAPSHOT.jar 1
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: us/codecraft/webmagic
/processor/PageProcessor
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.lang.Class.privateGetMethodRecursive(Unknown Source)
        at java.lang.Class.getMethod0(Unknown Source)
        at java.lang.Class.getMethod(Unknown Source)
        at sun.launcher.LauncherHelper.validateMainClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Caused by: java.lang.ClassNotFoundException: us.codecraft.webmagic.processor.Pag
eProcessor
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 7 more

I run application in eclipse . It is ok, But run from command error as above
Help me, thanks!

**Comment by zbclove** [comment]
I think you got an error when packaging source code to the jar.
