### ISSUE TITLE
Xsoup不支持not

### ISSUE THREAD

**Issue by CarlZhu93** [code4craft/webmagic#813]
Exception in thread "main" org.jsoup.select.Selector$SelectorParseException: Could not parse query 'th[not(@class)]': unexpected token at 'not(@class)'
	at us.codecraft.xsoup.xevaluator.XPathParser.byFunction(XPathParser.java:260)
	at us.codecraft.xsoup.xevaluator.XPathParser.consumePredicates(XPathParser.java:231)
	at us.codecraft.xsoup.xevaluator.XPathParser.findElements(XPathParser.java:163)
	at us.codecraft.xsoup.xevaluator.XPathParser.parse(XPathParser.java:76)
	at us.codecraft.xsoup.xevaluator.XPathParser.parse(XPathParser.java:408)
	at us.codecraft.xsoup.xevaluator.XPathParser.combinator(XPathParser.java:110)
	at us.codecraft.xsoup.xevaluator.XPathParser.parse(XPathParser.java:74)
	at us.codecraft.xsoup.xevaluator.XPathParser.parse(XPathParser.java:408)
	at us.codecraft.xsoup.Xsoup.compile(Xsoup.java:25)
	at us.codecraft.webmagic.selector.XpathSelector.<init>(XpathSelector.java:21)
	at us.codecraft.webmagic.utils.ExtractorUtils.getSelector(ExtractorUtils.java:28)
	at us.codecraft.webmagic.model.PageModelExtractor.getAnnotationExtractBy(PageModelExtractor.java:129)
	at us.codecraft.webmagic.model.PageModelExtractor.init(PageModelExtractor.java:60)
	at us.codecraft.webmagic.model.PageModelExtractor.create(PageModelExtractor.java:50)
	at us.codecraft.webmagic.model.ModelPageProcessor.addPageModel(ModelPageProcessor.java:38)
	at us.codecraft.webmagic.model.ModelPageProcessor.create(ModelPageProcessor.java:31)
	at us.codecraft.webmagic.model.OOSpider.<init>(OOSpider.java:68)
	at us.codecraft.webmagic.model.OOSpider.create(OOSpider.java:89)

**Comment by lcsan** [comment]
xsoup是自定义的，就那么几个方法。[http://webmagic.io/docs/zh/posts/ch4-basic-page-processor/xsoup.html](http://webmagic.io/docs/zh/posts/ch4-basic-page-processor/xsoup.html)
