### ISSUE TITLE
Dependency conflict issue: Exception in thread "main" java.lang.NoSuchMethodError: caused by multiple versions of commons-io:commons-io:jar 

### ISSUE THREAD

**Issue by LeoAugust19** [code4craft/webmagic#816]
Hi, @code4craft , there are multiple versions of **commons-io:commons-io:jar** in **us.codecraft:webmagic-selenium:jar:0.7.3**. As shown in the following dependency tree, only 
the older version commons-io:commons-io:jar:1.3.2 will be loaded and the newer versions are shadowed, according to "Maven's nearest wins strategy".

However, the method **<org.apache.commons.io.FileUtils: boolean deleteQuietly(java.io.File)>** only included in >commons-io 2.x, as a result, an exception will be thrown when your project referencing the missing method, with the following stack trace:

### Stack trace
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.commons.io.FileUtils.deleteQuietly(Ljava/io/File;)Z
	at com.gargoylesoftware.htmlunit.DownloadedContent$OnFile.cleanUp(DownloadedContent.java:86)
	at com.gargoylesoftware.htmlunit.WebResponseData.cleanUp(WebResponseData.java:184)
	at com.gargoylesoftware.htmlunit.WebResponse.cleanUp(WebResponse.java:250)
	at com.gargoylesoftware.htmlunit.SgmlPage.cleanUp(SgmlPage.java:62)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.cleanUp(HtmlPage.java:310)
	at com.gargoylesoftware.htmlunit.TopLevelWindow.close(TopLevelWindow.java:121)
	at com.gargoylesoftware.htmlunit.WebClient.closeAllWindows(WebClient.java:1707)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.quit(HtmlUnitDriver.java:571)
	at us.codecraft.webmagic.downloader.selenium.WebDriverPool.closeAll(WebDriverPool.java:235)

### Dependency tree
us.codecraft:webmagic-selenium:jar:0.7.3
+- org.seleniumhq.selenium:selenium-java:jar:2.41.0:compile
|  +- org.seleniumhq.selenium:selenium-chrome-driver:jar:2.41.0:compile
|  |  \- (org.seleniumhq.selenium:selenium-remote-driver:jar:2.41.0:compile - omitted for duplicate)
|  +- org.seleniumhq.selenium:selenium-htmlunit-driver:jar:2.41.0:compile
|  |  +- (org.seleniumhq.selenium:selenium-remote-driver:jar:2.41.0:compile - omitted for duplicate)
|  |  +- net.sourceforge.htmlunit:htmlunit:jar:2.13:compile
|  |  |  +- xalan:xalan:jar:2.7.1:compile
|  |  |  +- net.sourceforge.cssparser:cssparser:jar:0.9.11:compile
|  |  |  |  \- org.w3c.css:sac:jar:1.3:compile
|  |  |  +- **(commons-io:commons-io:jar:2.4:compile - omitted for conflict with 2.2)**
|  |  |  +- (commons-logging:commons-logging:jar:1.1.3:compile - omitted for conflict with 1.2)
|  |  |  \- org.eclipse.jetty:jetty-websocket:jar:8.1.12.v20130726:compile
|  |  |     +- org.eclipse.jetty:jetty-util:jar:8.1.12.v20130726:compile
|  |  |     +- org.eclipse.jetty:jetty-io:jar:8.1.12.v20130726:compile
|  |  |     |  \- (org.eclipse.jetty:jetty-util:jar:8.1.12.v20130726:compile - omitted for duplicate)
|  |  |     \- org.eclipse.jetty:jetty-http:jar:8.1.12.v20130726:compile
|  |  |        \- (org.eclipse.jetty:jetty-io:jar:8.1.12.v20130726:compile - omitted for duplicate)
|  |  \- (org.apache.httpcomponents:httpclient:jar:4.5.2:compile - version managed from 4.3.1; omitted for duplicate)
|  +- org.seleniumhq.selenium:selenium-firefox-driver:jar:2.41.0:compile
|  |  +- (org.seleniumhq.selenium:selenium-remote-driver:jar:2.41.0:compile - omitted for duplicate)
|  |  +- **(commons-io:commons-io:jar:2.2:compile - omitted for conflict with 1.3.2)**
|  |  \- org.apache.commons:commons-exec:jar:1.1:compile
|  +- org.seleniumhq.selenium:selenium-support:jar:2.41.0:compile
|  |  \- org.seleniumhq.selenium:selenium-api:jar:2.41.0:compile
|  |     +- (com.google.guava:guava:jar:15.0:compile - omitted for duplicate)
|  |     \- (org.json:json:jar:20080701:compile - omitted for duplicate)
|  \- org.webbitserver:webbit:jar:0.4.14:compile
|     \- io.netty:netty:jar:3.5.2.Final:compile
+- us.codecraft:webmagic-core:jar:0.7.3:compile
|  +- org.apache.httpcomponents:httpclient:jar:4.5.2:compile
|  |  +- org.apache.httpcomponents:httpcore:jar:4.4.4:compile
|  |  +- commons-logging:commons-logging:jar:1.2:compile
|  |  \- commons-codec:commons-codec:jar:1.9:compile
|  +- org.jsoup:jsoup:jar:1.10.3:compile
|  +- **commons-io:commons-io:jar:1.3.2:compile**
|  +- com.jayway.jsonpath:json-path:jar:2.4.0:compile
|  |  +- net.minidev:json-smart:jar:2.3:compile
|  |  |  \- net.minidev:accessors-smart:jar:1.2:compile
|  |  |     \- org.ow2.asm:asm:jar:5.0.4:compile
|  |  \- (org.slf4j:slf4j-api:jar:1.7.6:compile - version managed from 1.7.25; omitted for duplicate)
|  \- com.alibaba:fastjson:jar:1.2.28:compile

### Solution
Upgrade commons-io to 2.4.

Thanks,

Regards,
Leo

**Comment by LeoAugust19** [comment]
@code4craft May I pull a request to fix this issue?

**Comment by LeoAugust19** [comment]
@code4craft By the way. This issue is detected by an automated test case generation tool.
As it is difficult to cover the complex branches, before testing we mutated the source code to force the branch condition **if(topLevelWindows_.contains(topWindow))** in method **WebClient.closeAllWindows()** to be "TRUE", to trigger its execution.

![2](https://user-images.githubusercontent.com/41102283/43508149-b1f9eb7e-95a1-11e8-92d2-2b1ff11db2fc.png)
Also, prune a branch in method **WebDriverPool.closeAll()**
**if(!b){
throw new IllegalStaeException("Already closed!");
}**
![1](https://user-images.githubusercontent.com/41102283/43508138-a84bb6ac-95a1-11e8-826c-ec0af5fc8573.png)

Then, we got the crash with the above stack trace!
Could you please check whether the mutated branches are reasonable in reality?

Anyway, removing the dependency conflict issue benefits the software maintenance.

Thanks again!

**Comment by LeoAugust19** [comment]
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.commons.io.FileUtils.deleteQuietly(Ljava/io/File;)Z
	at com.gargoylesoftware.htmlunit.DownloadedContent$OnFile.cleanUp(DownloadedContent.java:86)
	at com.gargoylesoftware.htmlunit.WebResponseData.cleanUp(WebResponseData.java:184)
	at com.gargoylesoftware.htmlunit.WebResponse.cleanUp(WebResponse.java:250)
	at com.gargoylesoftware.htmlunit.SgmlPage.cleanUp(SgmlPage.java:62)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.cleanUp(HtmlPage.java:310)
	at com.gargoylesoftware.htmlunit.TopLevelWindow.close(TopLevelWindow.java:121)
	at com.gargoylesoftware.htmlunit.WebClient.closeAllWindows(WebClient.java:1707)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.quit(HtmlUnitDriver.java:571)
	at us.codecraft.webmagic.downloader.selenium.WebDriverPool.closeAll(WebDriverPool.java:235)

**Comment by LeoAugust19** [comment]
@ouyanghuangzheng, Hi, May pull a request to fix this issue?

**Comment by fendo8888** [comment]
<dependency>
			<groupId>us.codecraft</groupId>
			<artifactId>webmagic-core</artifactId>
			<version>0.7.3</version>
			<exclusions>
				<exclusion>
					<artifactId>commons-io</artifactId>
					<groupId>org.apache.commons</groupId>
				</exclusion>
				<exclusion>
					<groupId>org.slf4j</groupId>
					<artifactId>slf4j-log4j12</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

这样？
