### ISSUE TITLE
关于爬虫异常，出现TLSv1.3的问题

### ISSUE THREAD

**Issue by zhenghanwen** [code4craft/webmagic#943]
`"C:\Program Files\Java\jdk1.8.0_221\bin\java.exe" "-javaagent:D:\IntelliJ IDEA 2019.3.3\lib\idea_rt.jar=58548:D:\IntelliJ IDEA 2019.3.3\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Java\jdk1.8.0_221\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_221\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_221\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_221\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_221\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_221\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_221\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_221\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_221\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_221\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_221\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_221\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_221\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_221\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_221\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_221\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_221\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_221\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_221\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_221\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_221\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_221\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_221\jre\lib\rt.jar;D:\workspace\myWebMagic\target\classes;D:\workspace\webmagic-core\target\classes;D:\localRepository\org\apache\httpcomponents\httpclient\4.5.2\httpclient-4.5.2.jar;D:\localRepository\org\apache\httpcomponents\httpcore\4.4.4\httpcore-4.4.4.jar;D:\localRepository\commons-logging\commons-logging\1.2\commons-logging-1.2.jar;D:\localRepository\commons-codec\commons-codec\1.9\commons-codec-1.9.jar;D:\localRepository\org\apache\commons\commons-lang3\3.1\commons-lang3-3.1.jar;D:\localRepository\us\codecraft\xsoup\0.3.1\xsoup-0.3.1.jar;D:\localRepository\org\assertj\assertj-core\1.5.0\assertj-core-1.5.0.jar;D:\localRepository\commons-collections\commons-collections\3.2.2\commons-collections-3.2.2.jar;D:\localRepository\org\jsoup\jsoup\1.10.3\jsoup-1.10.3.jar;D:\localRepository\commons-io\commons-io\2.4\commons-io-2.4.jar;D:\localRepository\com\jayway\jsonpath\json-path\2.4.0\json-path-2.4.0.jar;D:\localRepository\net\minidev\json-smart\2.3\json-smart-2.3.jar;D:\localRepository\net\minidev\accessors-smart\1.2\accessors-smart-1.2.jar;D:\localRepository\org\ow2\asm\asm\5.0.4\asm-5.0.4.jar;D:\localRepository\com\alibaba\fastjson\1.2.28\fastjson-1.2.28.jar;D:\localRepository\us\codecraft\webmagic-extension\0.7.3\webmagic-extension-0.7.3.jar;D:\localRepository\redis\clients\jedis\2.9.0\jedis-2.9.0.jar;D:\localRepository\org\apache\commons\commons-pool2\2.4.2\commons-pool2-2.4.2.jar;D:\localRepository\org\slf4j\slf4j-api\1.7.25\slf4j-api-1.7.25.jar;D:\localRepository\ch\qos\logback\logback-core\1.2.3\logback-core-1.2.3.jar;D:\localRepository\ch\qos\logback\logback-classic\1.2.3\logback-classic-1.2.3.jar" MyCnblogsSpider
11:35:25.222 [main] DEBUG us.codecraft.webmagic.scheduler.QueueScheduler - push to queue http://www.cnblogs.com/justcooooode/
11:35:25.522 [main] DEBUG us.codecraft.webmagic.downloader.HttpClientGenerator - supportedProtocols: SSLv3, TLSv1, TLSv1.1, TLSv1.2, TLSv1.3
11:35:25.569 [main] INFO us.codecraft.webmagic.Spider - Spider www.cnblogs.com started!
11:35:25.884 [pool-1-thread-1] ERROR us.codecraft.webmagic.Spider - process request Request{url='http://www.cnblogs.com/justcooooode/', method='null', extras=null, priority=0, headers={}, cookies={}} error
java.lang.IllegalArgumentException: TLSv1.3
	at sun.security.ssl.ProtocolVersion.valueOf(ProtocolVersion.java:187)
	at sun.security.ssl.ProtocolList.convert(ProtocolList.java:84)
	at sun.security.ssl.ProtocolList.<init>(ProtocolList.java:52)
	at sun.security.ssl.SSLSocketImpl.setEnabledProtocols(SSLSocketImpl.java:2534)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:369)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:353)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at us.codecraft.webmagic.downloader.HttpClientDownloader.download(HttpClientDownloader.java:83)
	at us.codecraft.webmagic.Spider.processRequest(Spider.java:404)
	at us.codecraft.webmagic.Spider.access$000(Spider.java:61)
	at us.codecraft.webmagic.Spider$1.run(Spider.java:320)
	at us.codecraft.webmagic.thread.CountableThreadPool$1.run(CountableThreadPool.java:74)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
11:35:25.885 [main] INFO us.codecraft.webmagic.Spider - Spider www.cnblogs.com closed! 1 pages downloaded.

Process finished with exit code 0
`

**Comment by sutra** [comment]
这个问题应该在 3e425231414d41bd2d7ce1500d3e36fb610754fb 避免了，重新编译一下你的 webmagic 吧。
