### ISSUE TITLE
xpath 支持问题：positon() --->//table[@id='list_table']/tbody/tr[position()>1]

### ISSUE THREAD

**Issue by shizhier** [code4craft/webmagic#995]
html.xpath("//table[@id='list_table']/tbody/tr[position()>1]");
org.jsoup.select.Selector$SelectorParseException: Could not parse query 'tr[position()>1]': unexpected token at 'position()>1'
	at us.codecraft.xsoup.xevaluator.XPathParser.byFunction(XPathParser.java:260)
	at us.codecraft.xsoup.xevaluator.XPathParser.consumePredicates(XPathParser.java:231)
	at us.codecraft.xsoup.xevaluator.XPathParser.findElements(XPathParser.java:163)
	at us.codecraft.xsoup.xevaluator.XPathParser.parse(XPathParser.java:76)
	at us.codecraft.xsoup.xevaluator.XPathParser.parse(XPathParser.java:408)
	at us.codecraft.xsoup.xevaluator.XPathParser.combinator(XPathParser.java:110)
	at us.codecraft.xsoup.xevaluator.XPathParser.parse(XPathParser.java:74)
	at us.codecraft.xsoup.xevaluator.XPathParser.parse(XPathParser.java:408)
	at us.codecraft.xsoup.Xsoup.compile(Xsoup.java:25)
	at us.codecraft.webmagic.selector.XpathSelector.<init>(XpathSelector.java:21)
	at us.codecraft.webmagic.selector.Selectors.xpath(Selectors.java:32)
	at us.codecraft.webmagic.selector.HtmlNode.xpath(HtmlNode.java:42)
	at com.datage.dms.spider.spider.SichuanConstructionIndustryDataSharePlatform.process(SichuanConstructionIndustryDataSharePlatform.java:42)

**Comment by yuweiming2016** [comment]
xpath支持得不是很好，作者自己写的，用正则或者css吧

**Comment by sutra** [comment]
试试这个： https://github.com/code4craft/webmagic/issues/984#issuecomment-760695694

**Comment by shizhier** [comment]
webmagic是个很好的开源项目。基于java的生态，如果能长远的发展下去，很不错。慢慢成长。

Sutra Zhou <notifications@github.com> 于2021年2月5日周五 下午3:03写道：
